BaseWebSolution/Controllers/ExcelController.cs
using ExcelConfig;
using ExcelGen.Base;
using ExcelGen.Custom;
using ExcelGen.Custom.Base;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseWebSolution.Controllers
{
    public class ExcelController : Controller
    {
        //
        // GET: /Excel/

        public ActionResult Index(int id)
        {
            ActionResult result = View();


            // set the configuration for injecting into the excel generator 
            ExcelTemplateFileConfig config = new ExcelTemplateFileConfig
            {
                ApplicationPath = HttpContext.Server.MapPath("~"),
                TemplateFolderPath = ConfigurationManager.AppSettings["ExcelTemplateFolder"].ToString(),
                TemplateFileName = ConfigurationManager.AppSettings["ExcelTemplateFileName"].ToString(),
                TemporaryFolderPath = ConfigurationManager.AppSettings["ExcelTempFolder"].ToString(),
                TemporaryFileNameFormat = ConfigurationManager.AppSettings["ExcelTempFileNameFormat"].ToString(),
                FileDownloadName = ExcelFile.DefaultDownloadFileName
            };

            // set the configuration for injecting into the excel generators (includes save to location)
            ExcelSaveTemplateFileConfig configSave = new ExcelSaveTemplateFileConfig
            {
                ApplicationPath = HttpContext.Server.MapPath("~"),
                TemplateFolderPath = ConfigurationManager.AppSettings["ExcelTemplateFolder"].ToString(),
                TemplateFileName = ConfigurationManager.AppSettings["ExcelTemplateFileName"].ToString(),
                TemporaryFolderPath = ConfigurationManager.AppSettings["ExcelTempFolder"].ToString(),
                TemporaryFileNameFormat = ConfigurationManager.AppSettings["ExcelTempFileNameFormat"].ToString(),
                FileDownloadName = ExcelFile.DefaultDownloadFileName,
                OutputFolderPath = ConfigurationManager.AppSettings["ExcelOutputFolder"].ToString(),
                OutputFileNameFormat = ConfigurationManager.AppSettings["ExcelOutputFileNameFormat"].ToString()
            };

            
            

            TemplateExcelFile templateExcelFile;

            switch (id)
            {
                case 1:
                    using (templateExcelFile = new CustomSaveTemplateExcelFile(configSave))
                    {
                        templateExcelFile.Setup();
                    }
                    ViewBag.Message = String.Format("The excel file was saved to {0}", ((SaveTemplateExcelFile)templateExcelFile).OutputFilePath);
                    break;

                case 2:
                    using (templateExcelFile = new CustomStreamTemplateExcelFile(config))
                    {
                        templateExcelFile.Setup();
                        result = File(((StreamTemplateExcelFile)templateExcelFile).FileAsByteArray, ExcelFile.ContentType, templateExcelFile.FileDownloadName);
                    }
                    
                    break;

                default:
                    ViewBag.Message = String.Format("There was no excel file for id = {0}.", id);
                    break;
            }

            return result;

        }

    }
}

BaseWebSolution/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseWebSolution.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BaseWebSolution/Views/Excel/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BootstrapLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12 text-center">
        <h1>Excel Controller > Index View</h1>
        <h4>@ViewBag.Message</h4>
    </div>
</div>

BaseWebSolution/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

BaseWebSolution/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

BaseWebSolution/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-lg-12 text-center">
        <h1>Home Controller > Index View</h1>
        
    </div>
</div>
<!-- /.row -->

BaseWebSolution/Views/Shared/_BootstrapLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>@ViewBag.Title</title>
    <!-- Bootstrap Core CSS -->
    @Styles.Render("~/bundles/css")

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">logo</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Excel<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Excel #1", "Index", "Excel", new { id = 1 }, null)</li>
                            <li>@Html.ActionLink("Excel #2", "Index", "Excel", new { id = 2 }, null)</li>
                        </ul>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        @RenderBody()
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @Scripts.Render("~/bundles/jquery", "~/bundles/js")
</body>
</html>